---
name: Spotify Connect (dev branch)
version: dev
slug: spotify-dev
description: Play Spotify music on your Home Assistant device
url: https://github.com/FabioGNR/addon-spotify-connect
# codenotary: codenotary@frenck.dev
arch:
  - aarch64
  - amd64
  - armv7
host_network: true
audio: true
init: false
options:
  name: Home Assistant
  bitrate: 160
  enable_cache: false
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  name: str
  bitrate: list(96|160|320)
  initial_volume: int(0,100)?
  enable_cache: bool
  credentials_json: str?